[package]
name = "validation"
version = "0.1.0"
edition = "2018"

[dependencies]
candid = "0.10.13"
ic-cdk = "0.17.1"
serde_json = "1.0.82"
serde = { workspace = true }
hex = "0.4.3"
num-bigint = "0.4.3"
errors = { path = "../errors" }
types = { path = "../types" }